name: CI

on: [push, pull_request]

jobs:
  CI:
    runs-on: [self-hosted, linux, x64]

    steps:
      - uses: actions/checkout@v4

      - name: Créer fichier .env 
        run: |
          echo "POSTGRES_DB=brokerx" >> .env
          echo "POSTGRES_USER=brokerx_user" >> .env
          echo "POSTGRES_PASSWORD=0fvmdlsgjd68G3fgh8Gv3" >> .env
          echo "SPRING_DATASOURCE_USERNAME=brokerx_user" >> .env
          echo "SPRING_DATASOURCE_PASSWORD=0fvmdlsgjd68G3fgh8Gv3" >> .env

      - name: Déploiement
        working-directory: src
        run: echo "TODO - Faire le déploiement"

      - name: Cleanup
        if: always()
        run: docker compose down -v